triggers:
- description: null
  envs: []
  last_enabled_at: 2024-07-02 10:33:46.967728+00:00
  name: automatic_trigger
  pipeline_uuid: ingest
  schedule_interval: '@daily'
  schedule_type: time
  settings:
    landing_time_enabled: false
  sla: null
  start_time: 2024-07-02 10:40:00+00:00
  status: active
  token: 8356b0de34aa483aa6eaa4ddf368fa35
  variables: {}
